### ISSUE TITLE
use `tracing` instead of `log`

### ISSUE THREAD

**Issue by sehz** [lmapii/globmatch#9]
Hi, Nice project.  

I would love to use this project but would prefer  `tracing` instead of `log`.
Thanks!

**Comment by lmapii** [comment]
There are only two locations where I'm using `log`, I could remove those and have `log` only as a development(test) dependency.

EDIT: The dependency to `log` remains, but that is due to the underlying crate `globset` that I'm using. I won't be able to change that.
